import { Airport } from "@/types";

export const airports: Airport[] = [
  // ── EUROPE ─────────────────────────────────────────────────
  { code: "LBG", name: "Paris-Le Bourget", city: "Paris", country: "France", coordinates: { lat: 48.9694, lng: 2.4414 } },
  { code: "CDG", name: "Charles de Gaulle", city: "Paris", country: "France", coordinates: { lat: 49.0097, lng: 2.5479 } },
  { code: "NCE", name: "Nice Côte d'Azur", city: "Nice", country: "France", coordinates: { lat: 43.6584, lng: 7.2159 } },
  { code: "LYS", name: "Lyon-Saint Exupéry", city: "Lyon", country: "France", coordinates: { lat: 45.7256, lng: 5.0811 } },
  { code: "MRS", name: "Marseille Provence", city: "Marseille", country: "France", coordinates: { lat: 43.4393, lng: 5.2214 } },
  { code: "TLS", name: "Toulouse-Blagnac", city: "Toulouse", country: "France", coordinates: { lat: 43.6291, lng: 1.3638 } },
  { code: "BOD", name: "Bordeaux-Mérignac", city: "Bordeaux", country: "France", coordinates: { lat: 44.8283, lng: -0.7156 } },
  { code: "LTN", name: "London Luton", city: "London", country: "United Kingdom", coordinates: { lat: 51.8747, lng: -0.3683 } },
  { code: "LHR", name: "London Heathrow", city: "London", country: "United Kingdom", coordinates: { lat: 51.47, lng: -0.4543 } },
  { code: "LGW", name: "London Gatwick", city: "London", country: "United Kingdom", coordinates: { lat: 51.1537, lng: -0.1821 } },
  { code: "MAN", name: "Manchester Airport", city: "Manchester", country: "United Kingdom", coordinates: { lat: 53.3537, lng: -2.275 } },
  { code: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "United Kingdom", coordinates: { lat: 55.95, lng: -3.3725 } },
  { code: "BHX", name: "Birmingham Airport", city: "Birmingham", country: "United Kingdom", coordinates: { lat: 52.4539, lng: -1.748 } },
  { code: "GLA", name: "Glasgow Airport", city: "Glasgow", country: "United Kingdom", coordinates: { lat: 55.8719, lng: -4.4331 } },
  { code: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany", coordinates: { lat: 50.0379, lng: 8.5622 } },
  { code: "MUC", name: "Munich Airport", city: "Munich", country: "Germany", coordinates: { lat: 48.3537, lng: 11.775 } },
  { code: "TXL", name: "Berlin Brandenburg", city: "Berlin", country: "Germany", coordinates: { lat: 52.362, lng: 13.5099 } },
  { code: "HAM", name: "Hamburg Airport", city: "Hamburg", country: "Germany", coordinates: { lat: 53.6304, lng: 9.9882 } },
  { code: "DUS", name: "Düsseldorf Airport", city: "Düsseldorf", country: "Germany", coordinates: { lat: 51.2895, lng: 6.7668 } },
  { code: "CGN", name: "Cologne Bonn Airport", city: "Cologne", country: "Germany", coordinates: { lat: 50.8659, lng: 7.1427 } },
  { code: "STR", name: "Stuttgart Airport", city: "Stuttgart", country: "Germany", coordinates: { lat: 48.69, lng: 9.2219 } },
  { code: "MAD", name: "Adolfo Suárez Madrid-Barajas", city: "Madrid", country: "Spain", coordinates: { lat: 40.4719, lng: -3.5626 } },
  { code: "BCN", name: "Barcelona–El Prat", city: "Barcelona", country: "Spain", coordinates: { lat: 41.2971, lng: 2.0785 } },
  { code: "AGP", name: "Málaga Airport", city: "Málaga", country: "Spain", coordinates: { lat: 36.675, lng: -4.499 } },
  { code: "PMI", name: "Palma de Mallorca", city: "Palma", country: "Spain", coordinates: { lat: 39.5517, lng: 2.7388 } },
  { code: "IBZ", name: "Ibiza Airport", city: "Ibiza", country: "Spain", coordinates: { lat: 38.8729, lng: 1.3731 } },
  { code: "VLC", name: "Valencia Airport", city: "Valencia", country: "Spain", coordinates: { lat: 39.4893, lng: -0.4816 } },
  { code: "SVQ", name: "Seville Airport", city: "Seville", country: "Spain", coordinates: { lat: 37.418, lng: -5.8931 } },
  { code: "FCO", name: "Leonardo da Vinci–Fiumicino", city: "Rome", country: "Italy", coordinates: { lat: 41.8003, lng: 12.2389 } },
  { code: "MXP", name: "Malpensa", city: "Milan", country: "Italy", coordinates: { lat: 45.6306, lng: 8.7281 } },
  { code: "VCE", name: "Venice Marco Polo", city: "Venice", country: "Italy", coordinates: { lat: 45.5053, lng: 12.3519 } },
  { code: "NAP", name: "Naples International", city: "Naples", country: "Italy", coordinates: { lat: 40.886, lng: 14.2908 } },
  { code: "FLR", name: "Florence Peretola", city: "Florence", country: "Italy", coordinates: { lat: 43.81, lng: 11.2051 } },
  { code: "OLB", name: "Olbia Costa Smeralda", city: "Olbia", country: "Italy", coordinates: { lat: 40.8987, lng: 9.5176 } },
  { code: "AMS", name: "Amsterdam Schiphol", city: "Amsterdam", country: "Netherlands", coordinates: { lat: 52.3105, lng: 4.7683 } },
  { code: "BRU", name: "Brussels Airport", city: "Brussels", country: "Belgium", coordinates: { lat: 50.9014, lng: 4.4844 } },
  { code: "ZRH", name: "Zürich Airport", city: "Zürich", country: "Switzerland", coordinates: { lat: 47.4647, lng: 8.5492 } },
  { code: "GVA", name: "Geneva-Cointrin", city: "Geneva", country: "Switzerland", coordinates: { lat: 46.2381, lng: 6.1089 } },
  { code: "LUG", name: "Lugano Airport", city: "Lugano", country: "Switzerland", coordinates: { lat: 46.0044, lng: 8.9106 } },
  { code: "VIE", name: "Vienna International", city: "Vienna", country: "Austria", coordinates: { lat: 48.1103, lng: 16.5697 } },
  { code: "SZG", name: "Salzburg Airport", city: "Salzburg", country: "Austria", coordinates: { lat: 47.7933, lng: 13.0043 } },
  { code: "INN", name: "Innsbruck Airport", city: "Innsbruck", country: "Austria", coordinates: { lat: 47.2602, lng: 11.344 } },
  { code: "LIS", name: "Lisbon Portela", city: "Lisbon", country: "Portugal", coordinates: { lat: 38.7813, lng: -9.1359 } },
  { code: "OPO", name: "Porto Airport", city: "Porto", country: "Portugal", coordinates: { lat: 41.2481, lng: -8.6814 } },
  { code: "FAO", name: "Faro Airport", city: "Faro", country: "Portugal", coordinates: { lat: 37.0144, lng: -7.9659 } },
  { code: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland", coordinates: { lat: 53.4213, lng: -6.2701 } },
  { code: "SNN", name: "Shannon Airport", city: "Shannon", country: "Ireland", coordinates: { lat: 52.702, lng: -8.9248 } },
  { code: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "Denmark", coordinates: { lat: 55.618, lng: 12.656 } },
  { code: "OSL", name: "Oslo Gardermoen", city: "Oslo", country: "Norway", coordinates: { lat: 60.1976, lng: 11.1004 } },
  { code: "BGO", name: "Bergen Flesland", city: "Bergen", country: "Norway", coordinates: { lat: 60.2934, lng: 5.2181 } },
  { code: "ARN", name: "Stockholm Arlanda", city: "Stockholm", country: "Sweden", coordinates: { lat: 59.6519, lng: 17.9186 } },
  { code: "GOT", name: "Gothenburg Landvetter", city: "Gothenburg", country: "Sweden", coordinates: { lat: 57.6628, lng: 12.2798 } },
  { code: "HEL", name: "Helsinki-Vantaa", city: "Helsinki", country: "Finland", coordinates: { lat: 60.3172, lng: 24.9633 } },
  { code: "KEF", name: "Keflavík International", city: "Reykjavik", country: "Iceland", coordinates: { lat: 63.985, lng: -22.6056 } },
  { code: "WAW", name: "Warsaw Chopin", city: "Warsaw", country: "Poland", coordinates: { lat: 52.1657, lng: 20.9671 } },
  { code: "KRK", name: "John Paul II International", city: "Kraków", country: "Poland", coordinates: { lat: 50.0777, lng: 19.7848 } },
  { code: "PRG", name: "Václav Havel Airport", city: "Prague", country: "Czech Republic", coordinates: { lat: 50.1008, lng: 14.26 } },
  { code: "BUD", name: "Budapest Ferenc Liszt", city: "Budapest", country: "Hungary", coordinates: { lat: 47.4398, lng: 19.2556 } },
  { code: "OTP", name: "Henri Coandă International", city: "Bucharest", country: "Romania", coordinates: { lat: 44.5711, lng: 26.085 } },
  { code: "SOF", name: "Sofia Airport", city: "Sofia", country: "Bulgaria", coordinates: { lat: 42.6952, lng: 23.4062 } },
  { code: "ATH", name: "Athens International", city: "Athens", country: "Greece", coordinates: { lat: 37.9364, lng: 23.9445 } },
  { code: "SKG", name: "Thessaloniki Airport", city: "Thessaloniki", country: "Greece", coordinates: { lat: 40.5197, lng: 22.9709 } },
  { code: "JMK", name: "Mykonos Airport", city: "Mykonos", country: "Greece", coordinates: { lat: 37.4351, lng: 25.3481 } },
  { code: "JTR", name: "Santorini Airport", city: "Santorini", country: "Greece", coordinates: { lat: 36.3992, lng: 25.4793 } },
  { code: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey", coordinates: { lat: 41.2753, lng: 28.7519 } },
  { code: "AYT", name: "Antalya Airport", city: "Antalya", country: "Turkey", coordinates: { lat: 36.8987, lng: 30.8005 } },
  { code: "DLM", name: "Dalaman Airport", city: "Dalaman", country: "Turkey", coordinates: { lat: 36.7131, lng: 28.7925 } },
  { code: "BJV", name: "Milas–Bodrum Airport", city: "Bodrum", country: "Turkey", coordinates: { lat: 37.2506, lng: 27.6643 } },
  { code: "BEG", name: "Belgrade Nikola Tesla", city: "Belgrade", country: "Serbia", coordinates: { lat: 44.8184, lng: 20.309 } },
  { code: "ZAG", name: "Zagreb Airport", city: "Zagreb", country: "Croatia", coordinates: { lat: 45.7429, lng: 16.0688 } },
  { code: "DBV", name: "Dubrovnik Airport", city: "Dubrovnik", country: "Croatia", coordinates: { lat: 42.5614, lng: 18.2682 } },
  { code: "SPU", name: "Split Airport", city: "Split", country: "Croatia", coordinates: { lat: 43.5389, lng: 16.298 } },
  { code: "LJU", name: "Ljubljana Airport", city: "Ljubljana", country: "Slovenia", coordinates: { lat: 46.2237, lng: 14.4576 } },
  { code: "TIV", name: "Tivat Airport", city: "Tivat", country: "Montenegro", coordinates: { lat: 42.4047, lng: 18.7233 } },
  { code: "TIA", name: "Tirana International", city: "Tirana", country: "Albania", coordinates: { lat: 41.4147, lng: 19.7206 } },
  { code: "SKP", name: "Skopje International", city: "Skopje", country: "North Macedonia", coordinates: { lat: 41.9616, lng: 21.6214 } },
  { code: "SVO", name: "Sheremetyevo", city: "Moscow", country: "Russia", coordinates: { lat: 55.9726, lng: 37.4146 } },
  { code: "LED", name: "Pulkovo Airport", city: "Saint Petersburg", country: "Russia", coordinates: { lat: 59.8003, lng: 30.2625 } },
  { code: "KBP", name: "Boryspil International", city: "Kyiv", country: "Ukraine", coordinates: { lat: 50.345, lng: 30.8947 } },
  { code: "RIX", name: "Riga International", city: "Riga", country: "Latvia", coordinates: { lat: 56.9236, lng: 23.9711 } },
  { code: "VNO", name: "Vilnius Airport", city: "Vilnius", country: "Lithuania", coordinates: { lat: 54.6341, lng: 25.2858 } },
  { code: "TLL", name: "Tallinn Airport", city: "Tallinn", country: "Estonia", coordinates: { lat: 59.4133, lng: 24.8328 } },
  { code: "LUX", name: "Luxembourg Airport", city: "Luxembourg", country: "Luxembourg", coordinates: { lat: 49.6233, lng: 6.2044 } },
  { code: "MLA", name: "Malta International", city: "Valletta", country: "Malta", coordinates: { lat: 35.8575, lng: 14.4775 } },
  { code: "LCA", name: "Larnaca International", city: "Larnaca", country: "Cyprus", coordinates: { lat: 34.8751, lng: 33.6249 } },
  { code: "PFO", name: "Paphos International", city: "Paphos", country: "Cyprus", coordinates: { lat: 34.718, lng: 32.4857 } },

  // ── NORTH AMERICA ──────────────────────────────────────────
  { code: "TEB", name: "Teterboro", city: "New York", country: "United States", coordinates: { lat: 40.8501, lng: -74.0608 } },
  { code: "JFK", name: "John F. Kennedy Intl", city: "New York", country: "United States", coordinates: { lat: 40.6413, lng: -73.7781 } },
  { code: "EWR", name: "Newark Liberty Intl", city: "Newark", country: "United States", coordinates: { lat: 40.6895, lng: -74.1745 } },
  { code: "VNY", name: "Van Nuys", city: "Los Angeles", country: "United States", coordinates: { lat: 34.2098, lng: -118.49 } },
  { code: "LAX", name: "Los Angeles Intl", city: "Los Angeles", country: "United States", coordinates: { lat: 33.9425, lng: -118.408 } },
  { code: "OPF", name: "Opa-Locka Executive", city: "Miami", country: "United States", coordinates: { lat: 25.907, lng: -80.2784 } },
  { code: "MIA", name: "Miami International", city: "Miami", country: "United States", coordinates: { lat: 25.7959, lng: -80.287 } },
  { code: "ORD", name: "O'Hare International", city: "Chicago", country: "United States", coordinates: { lat: 41.9742, lng: -87.9073 } },
  { code: "ATL", name: "Hartsfield-Jackson", city: "Atlanta", country: "United States", coordinates: { lat: 33.6407, lng: -84.4277 } },
  { code: "DFW", name: "Dallas/Fort Worth Intl", city: "Dallas", country: "United States", coordinates: { lat: 32.8998, lng: -97.0403 } },
  { code: "IAH", name: "George Bush Intercontinental", city: "Houston", country: "United States", coordinates: { lat: 29.9902, lng: -95.3368 } },
  { code: "SFO", name: "San Francisco Intl", city: "San Francisco", country: "United States", coordinates: { lat: 37.6213, lng: -122.379 } },
  { code: "SEA", name: "Seattle-Tacoma Intl", city: "Seattle", country: "United States", coordinates: { lat: 47.4502, lng: -122.3088 } },
  { code: "DEN", name: "Denver International", city: "Denver", country: "United States", coordinates: { lat: 39.8561, lng: -104.6737 } },
  { code: "BOS", name: "Logan International", city: "Boston", country: "United States", coordinates: { lat: 42.3656, lng: -71.0096 } },
  { code: "LAS", name: "Harry Reid International", city: "Las Vegas", country: "United States", coordinates: { lat: 36.084, lng: -115.1537 } },
  { code: "PHX", name: "Phoenix Sky Harbor", city: "Phoenix", country: "United States", coordinates: { lat: 33.4373, lng: -112.0078 } },
  { code: "MSP", name: "Minneapolis-Saint Paul Intl", city: "Minneapolis", country: "United States", coordinates: { lat: 44.8848, lng: -93.2223 } },
  { code: "DTW", name: "Detroit Metropolitan", city: "Detroit", country: "United States", coordinates: { lat: 42.2162, lng: -83.3554 } },
  { code: "PHL", name: "Philadelphia International", city: "Philadelphia", country: "United States", coordinates: { lat: 39.8721, lng: -75.2411 } },
  { code: "DCA", name: "Ronald Reagan Washington", city: "Washington D.C.", country: "United States", coordinates: { lat: 38.8512, lng: -77.0402 } },
  { code: "IAD", name: "Dulles International", city: "Washington D.C.", country: "United States", coordinates: { lat: 38.9531, lng: -77.4565 } },
  { code: "SAN", name: "San Diego International", city: "San Diego", country: "United States", coordinates: { lat: 32.7336, lng: -117.1897 } },
  { code: "TPA", name: "Tampa International", city: "Tampa", country: "United States", coordinates: { lat: 27.9755, lng: -82.5332 } },
  { code: "MCO", name: "Orlando International", city: "Orlando", country: "United States", coordinates: { lat: 28.4312, lng: -81.308 } },
  { code: "MSY", name: "Louis Armstrong Intl", city: "New Orleans", country: "United States", coordinates: { lat: 29.9934, lng: -90.258 } },
  { code: "HNL", name: "Daniel K. Inouye Intl", city: "Honolulu", country: "United States", coordinates: { lat: 21.3187, lng: -157.9225 } },
  { code: "ANC", name: "Ted Stevens Anchorage", city: "Anchorage", country: "United States", coordinates: { lat: 61.1743, lng: -149.9962 } },
  { code: "PDX", name: "Portland International", city: "Portland", country: "United States", coordinates: { lat: 45.5898, lng: -122.5951 } },
  { code: "CLT", name: "Charlotte Douglas Intl", city: "Charlotte", country: "United States", coordinates: { lat: 35.214, lng: -80.9431 } },
  { code: "SLC", name: "Salt Lake City Intl", city: "Salt Lake City", country: "United States", coordinates: { lat: 40.7884, lng: -111.9778 } },
  { code: "BNA", name: "Nashville International", city: "Nashville", country: "United States", coordinates: { lat: 36.1263, lng: -86.6774 } },
  { code: "RDU", name: "Raleigh-Durham Intl", city: "Raleigh", country: "United States", coordinates: { lat: 35.8801, lng: -78.7875 } },
  { code: "ASE", name: "Aspen/Pitkin County", city: "Aspen", country: "United States", coordinates: { lat: 39.2232, lng: -106.8689 } },
  { code: "YYZ", name: "Toronto Pearson", city: "Toronto", country: "Canada", coordinates: { lat: 43.6777, lng: -79.6248 } },
  { code: "YVR", name: "Vancouver International", city: "Vancouver", country: "Canada", coordinates: { lat: 49.1947, lng: -123.1792 } },
  { code: "YUL", name: "Montréal-Trudeau", city: "Montréal", country: "Canada", coordinates: { lat: 45.4706, lng: -73.7408 } },
  { code: "YOW", name: "Ottawa Macdonald-Cartier", city: "Ottawa", country: "Canada", coordinates: { lat: 45.3225, lng: -75.6692 } },
  { code: "YYC", name: "Calgary International", city: "Calgary", country: "Canada", coordinates: { lat: 51.1215, lng: -114.0076 } },
  { code: "YEG", name: "Edmonton International", city: "Edmonton", country: "Canada", coordinates: { lat: 53.3097, lng: -113.5797 } },
  { code: "YHZ", name: "Halifax Stanfield Intl", city: "Halifax", country: "Canada", coordinates: { lat: 44.8808, lng: -63.5086 } },
  { code: "YWG", name: "Winnipeg Richardson Intl", city: "Winnipeg", country: "Canada", coordinates: { lat: 49.91, lng: -97.2399 } },
  { code: "MEX", name: "Mexico City International", city: "Mexico City", country: "Mexico", coordinates: { lat: 19.4363, lng: -99.0721 } },
  { code: "CUN", name: "Cancún International", city: "Cancún", country: "Mexico", coordinates: { lat: 21.0365, lng: -86.8771 } },
  { code: "GDL", name: "Guadalajara International", city: "Guadalajara", country: "Mexico", coordinates: { lat: 20.5218, lng: -103.3114 } },
  { code: "SJD", name: "Los Cabos International", city: "San José del Cabo", country: "Mexico", coordinates: { lat: 23.1518, lng: -109.7215 } },
  { code: "PVR", name: "Puerto Vallarta Intl", city: "Puerto Vallarta", country: "Mexico", coordinates: { lat: 20.6801, lng: -105.2544 } },
  { code: "MTY", name: "Monterrey International", city: "Monterrey", country: "Mexico", coordinates: { lat: 25.7785, lng: -100.107 } },

  // ── CARIBBEAN & CENTRAL AMERICA ────────────────────────────
  { code: "NAS", name: "Lynden Pindling Intl", city: "Nassau", country: "Bahamas", coordinates: { lat: 25.039, lng: -77.4662 } },
  { code: "MBJ", name: "Sangster International", city: "Montego Bay", country: "Jamaica", coordinates: { lat: 18.5037, lng: -77.9134 } },
  { code: "KIN", name: "Norman Manley Intl", city: "Kingston", country: "Jamaica", coordinates: { lat: 17.9357, lng: -76.7875 } },
  { code: "PUJ", name: "Punta Cana International", city: "Punta Cana", country: "Dominican Republic", coordinates: { lat: 18.5674, lng: -68.3634 } },
  { code: "SDQ", name: "Las Américas International", city: "Santo Domingo", country: "Dominican Republic", coordinates: { lat: 18.4297, lng: -69.6689 } },
  { code: "SJU", name: "Luis Muñoz Marín", city: "San Juan", country: "Puerto Rico", coordinates: { lat: 18.4394, lng: -66.0018 } },
  { code: "HAV", name: "José Martí International", city: "Havana", country: "Cuba", coordinates: { lat: 22.9892, lng: -82.4091 } },
  { code: "POS", name: "Piarco International", city: "Port of Spain", country: "Trinidad & Tobago", coordinates: { lat: 10.5954, lng: -61.3372 } },
  { code: "BGI", name: "Grantley Adams Intl", city: "Bridgetown", country: "Barbados", coordinates: { lat: 13.0746, lng: -59.4925 } },
  { code: "SXM", name: "Princess Juliana Intl", city: "Philipsburg", country: "Sint Maarten", coordinates: { lat: 18.041, lng: -63.1089 } },
  { code: "AUA", name: "Queen Beatrix Intl", city: "Oranjestad", country: "Aruba", coordinates: { lat: 12.5014, lng: -70.0152 } },
  { code: "CUR", name: "Hato International", city: "Willemstad", country: "Curaçao", coordinates: { lat: 12.1889, lng: -68.9598 } },
  { code: "GCM", name: "Owen Roberts Intl", city: "George Town", country: "Cayman Islands", coordinates: { lat: 19.2928, lng: -81.3577 } },
  { code: "PTP", name: "Pointe-à-Pitre Intl", city: "Pointe-à-Pitre", country: "Guadeloupe", coordinates: { lat: 16.2653, lng: -61.5318 } },
  { code: "FDF", name: "Aimé Césaire Intl", city: "Fort-de-France", country: "Martinique", coordinates: { lat: 14.591, lng: -61.0032 } },
  { code: "PTY", name: "Tocumen International", city: "Panama City", country: "Panama", coordinates: { lat: 9.0714, lng: -79.3835 } },
  { code: "SJO", name: "Juan Santamaría Intl", city: "San José", country: "Costa Rica", coordinates: { lat: 9.9939, lng: -84.2088 } },
  { code: "LIR", name: "Daniel Oduber Quirós", city: "Liberia", country: "Costa Rica", coordinates: { lat: 10.5933, lng: -85.5444 } },
  { code: "SAL", name: "Óscar Arnulfo Romero Intl", city: "San Salvador", country: "El Salvador", coordinates: { lat: 13.4409, lng: -89.0557 } },
  { code: "GUA", name: "La Aurora International", city: "Guatemala City", country: "Guatemala", coordinates: { lat: 14.5833, lng: -90.5275 } },
  { code: "BZE", name: "Philip S. W. Goldson Intl", city: "Belize City", country: "Belize", coordinates: { lat: 17.5391, lng: -88.3082 } },
  { code: "MGA", name: "Augusto C. Sandino Intl", city: "Managua", country: "Nicaragua", coordinates: { lat: 12.1415, lng: -86.1682 } },
  { code: "TGU", name: "Toncontín International", city: "Tegucigalpa", country: "Honduras", coordinates: { lat: 14.0609, lng: -87.2172 } },

  // ── SOUTH AMERICA ──────────────────────────────────────────
  { code: "GRU", name: "São Paulo–Guarulhos", city: "São Paulo", country: "Brazil", coordinates: { lat: -23.4356, lng: -46.4731 } },
  { code: "GIG", name: "Rio de Janeiro–Galeão", city: "Rio de Janeiro", country: "Brazil", coordinates: { lat: -22.8099, lng: -43.2506 } },
  { code: "BSB", name: "Brasília International", city: "Brasília", country: "Brazil", coordinates: { lat: -15.8711, lng: -47.9186 } },
  { code: "CNF", name: "Confins International", city: "Belo Horizonte", country: "Brazil", coordinates: { lat: -19.6244, lng: -43.9719 } },
  { code: "SSA", name: "Salvador International", city: "Salvador", country: "Brazil", coordinates: { lat: -12.9086, lng: -38.3225 } },
  { code: "REC", name: "Recife/Guararapes Intl", city: "Recife", country: "Brazil", coordinates: { lat: -8.1264, lng: -34.9236 } },
  { code: "FOR", name: "Fortaleza Pinto Martins", city: "Fortaleza", country: "Brazil", coordinates: { lat: -3.7763, lng: -38.5326 } },
  { code: "POA", name: "Porto Alegre International", city: "Porto Alegre", country: "Brazil", coordinates: { lat: -29.9944, lng: -51.1714 } },
  { code: "MAO", name: "Eduardo Gomes Intl", city: "Manaus", country: "Brazil", coordinates: { lat: -3.0386, lng: -60.0497 } },
  { code: "FLN", name: "Florianópolis Intl", city: "Florianópolis", country: "Brazil", coordinates: { lat: -27.6703, lng: -48.5525 } },
  { code: "EZE", name: "Ministro Pistarini", city: "Buenos Aires", country: "Argentina", coordinates: { lat: -34.8222, lng: -58.5358 } },
  { code: "AEP", name: "Aeroparque Jorge Newbery", city: "Buenos Aires", country: "Argentina", coordinates: { lat: -34.5592, lng: -58.4156 } },
  { code: "COR", name: "Córdoba Intl", city: "Córdoba", country: "Argentina", coordinates: { lat: -31.3236, lng: -64.208 } },
  { code: "MDZ", name: "Governor Francisco Gabrielli", city: "Mendoza", country: "Argentina", coordinates: { lat: -32.8317, lng: -68.7929 } },
  { code: "BRC", name: "San Carlos de Bariloche", city: "Bariloche", country: "Argentina", coordinates: { lat: -41.1512, lng: -71.1575 } },
  { code: "USH", name: "Ushuaia – Malvinas Argentinas", city: "Ushuaia", country: "Argentina", coordinates: { lat: -54.8433, lng: -68.3128 } },
  { code: "SCL", name: "Arturo Merino Benítez", city: "Santiago", country: "Chile", coordinates: { lat: -33.393, lng: -70.7858 } },
  { code: "IPC", name: "Mataveri International", city: "Easter Island", country: "Chile", coordinates: { lat: -27.1648, lng: -109.4219 } },
  { code: "PUQ", name: "Punta Arenas Airport", city: "Punta Arenas", country: "Chile", coordinates: { lat: -53.0026, lng: -70.8546 } },
  { code: "BOG", name: "El Dorado International", city: "Bogotá", country: "Colombia", coordinates: { lat: 4.7016, lng: -74.1469 } },
  { code: "MDE", name: "José María Córdova Intl", city: "Medellín", country: "Colombia", coordinates: { lat: 6.1645, lng: -75.4231 } },
  { code: "CTG", name: "Rafael Núñez International", city: "Cartagena", country: "Colombia", coordinates: { lat: 10.4424, lng: -75.513 } },
  { code: "CLO", name: "Alfonso Bonilla Aragón", city: "Cali", country: "Colombia", coordinates: { lat: 3.5432, lng: -76.3816 } },
  { code: "LIM", name: "Jorge Chávez International", city: "Lima", country: "Peru", coordinates: { lat: -12.0219, lng: -77.1143 } },
  { code: "CUZ", name: "Alejandro Velasco Astete", city: "Cusco", country: "Peru", coordinates: { lat: -13.5357, lng: -71.9388 } },
  { code: "UIO", name: "Mariscal Sucre International", city: "Quito", country: "Ecuador", coordinates: { lat: -0.1292, lng: -78.3575 } },
  { code: "GYE", name: "José Joaquín de Olmedo", city: "Guayaquil", country: "Ecuador", coordinates: { lat: -2.1574, lng: -79.8837 } },
  { code: "GPS", name: "Seymour Airport", city: "Galápagos", country: "Ecuador", coordinates: { lat: -0.4537, lng: -90.2659 } },
  { code: "CCS", name: "Simón Bolívar International", city: "Caracas", country: "Venezuela", coordinates: { lat: 10.6012, lng: -66.9913 } },
  { code: "VVI", name: "Viru Viru International", city: "Santa Cruz", country: "Bolivia", coordinates: { lat: -17.6448, lng: -63.1354 } },
  { code: "LPB", name: "El Alto International", city: "La Paz", country: "Bolivia", coordinates: { lat: -16.5133, lng: -68.1923 } },
  { code: "ASU", name: "Silvio Pettirossi Intl", city: "Asunción", country: "Paraguay", coordinates: { lat: -25.24, lng: -57.519 } },
  { code: "MVD", name: "Carrasco International", city: "Montevideo", country: "Uruguay", coordinates: { lat: -34.8384, lng: -56.0308 } },
  { code: "PBM", name: "Johan Adolf Pengel Intl", city: "Paramaribo", country: "Suriname", coordinates: { lat: 5.4531, lng: -55.1876 } },
  { code: "GEO", name: "Cheddi Jagan International", city: "Georgetown", country: "Guyana", coordinates: { lat: 6.4985, lng: -58.2541 } },
  { code: "CAY", name: "Cayenne – Félix Eboué", city: "Cayenne", country: "French Guiana", coordinates: { lat: 4.8198, lng: -52.3606 } },

  // ── MIDDLE EAST ────────────────────────────────────────────
  { code: "DXB", name: "Dubai International", city: "Dubai", country: "UAE", coordinates: { lat: 25.2532, lng: 55.3657 } },
  { code: "AUH", name: "Abu Dhabi International", city: "Abu Dhabi", country: "UAE", coordinates: { lat: 24.433, lng: 54.6511 } },
  { code: "DOH", name: "Hamad International", city: "Doha", country: "Qatar", coordinates: { lat: 25.2731, lng: 51.6081 } },
  { code: "RUH", name: "King Khalid International", city: "Riyadh", country: "Saudi Arabia", coordinates: { lat: 24.9578, lng: 46.6989 } },
  { code: "JED", name: "King Abdulaziz International", city: "Jeddah", country: "Saudi Arabia", coordinates: { lat: 21.6796, lng: 39.1565 } },
  { code: "DMM", name: "King Fahd International", city: "Dammam", country: "Saudi Arabia", coordinates: { lat: 26.4712, lng: 49.7979 } },
  { code: "MCT", name: "Muscat International", city: "Muscat", country: "Oman", coordinates: { lat: 23.5933, lng: 58.2844 } },
  { code: "BAH", name: "Bahrain International", city: "Manama", country: "Bahrain", coordinates: { lat: 26.2708, lng: 50.6336 } },
  { code: "KWI", name: "Kuwait International", city: "Kuwait City", country: "Kuwait", coordinates: { lat: 29.2266, lng: 47.9689 } },
  { code: "TLV", name: "Ben Gurion International", city: "Tel Aviv", country: "Israel", coordinates: { lat: 32.0055, lng: 34.8854 } },
  { code: "AMM", name: "Queen Alia International", city: "Amman", country: "Jordan", coordinates: { lat: 31.7226, lng: 35.9932 } },
  { code: "BEY", name: "Rafic Hariri International", city: "Beirut", country: "Lebanon", coordinates: { lat: 33.8209, lng: 35.4884 } },
  { code: "IKA", name: "Imam Khomeini International", city: "Tehran", country: "Iran", coordinates: { lat: 35.4161, lng: 51.1522 } },
  { code: "BGW", name: "Baghdad International", city: "Baghdad", country: "Iraq", coordinates: { lat: 33.2625, lng: 44.2346 } },
  { code: "EBL", name: "Erbil International", city: "Erbil", country: "Iraq", coordinates: { lat: 36.2376, lng: 43.9632 } },

  // ── ASIA ───────────────────────────────────────────────────
  { code: "NRT", name: "Narita International", city: "Tokyo", country: "Japan", coordinates: { lat: 35.7647, lng: 140.3864 } },
  { code: "HND", name: "Haneda", city: "Tokyo", country: "Japan", coordinates: { lat: 35.5494, lng: 139.7798 } },
  { code: "KIX", name: "Kansai International", city: "Osaka", country: "Japan", coordinates: { lat: 34.4347, lng: 135.244 } },
  { code: "NGO", name: "Chubu Centrair Intl", city: "Nagoya", country: "Japan", coordinates: { lat: 34.8584, lng: 136.8125 } },
  { code: "FUK", name: "Fukuoka Airport", city: "Fukuoka", country: "Japan", coordinates: { lat: 33.5859, lng: 130.4511 } },
  { code: "CTS", name: "New Chitose Airport", city: "Sapporo", country: "Japan", coordinates: { lat: 42.7752, lng: 141.6924 } },
  { code: "OKA", name: "Naha Airport", city: "Okinawa", country: "Japan", coordinates: { lat: 26.1958, lng: 127.6459 } },
  { code: "ICN", name: "Incheon International", city: "Seoul", country: "South Korea", coordinates: { lat: 37.4602, lng: 126.4407 } },
  { code: "GMP", name: "Gimpo International", city: "Seoul", country: "South Korea", coordinates: { lat: 37.5585, lng: 126.7906 } },
  { code: "PUS", name: "Gimhae International", city: "Busan", country: "South Korea", coordinates: { lat: 35.1796, lng: 128.938 } },
  { code: "CJU", name: "Jeju International", city: "Jeju", country: "South Korea", coordinates: { lat: 33.5113, lng: 126.493 } },
  { code: "PEK", name: "Beijing Capital", city: "Beijing", country: "China", coordinates: { lat: 40.0799, lng: 116.6031 } },
  { code: "PKX", name: "Beijing Daxing", city: "Beijing", country: "China", coordinates: { lat: 39.5098, lng: 116.4105 } },
  { code: "PVG", name: "Shanghai Pudong", city: "Shanghai", country: "China", coordinates: { lat: 31.1443, lng: 121.8083 } },
  { code: "CAN", name: "Guangzhou Baiyun", city: "Guangzhou", country: "China", coordinates: { lat: 23.3924, lng: 113.299 } },
  { code: "SZX", name: "Shenzhen Bao'an", city: "Shenzhen", country: "China", coordinates: { lat: 22.6393, lng: 113.8107 } },
  { code: "CTU", name: "Chengdu Tianfu", city: "Chengdu", country: "China", coordinates: { lat: 30.5785, lng: 104.0648 } },
  { code: "CKG", name: "Chongqing Jiangbei", city: "Chongqing", country: "China", coordinates: { lat: 29.7192, lng: 106.6417 } },
  { code: "XIY", name: "Xi'an Xianyang", city: "Xi'an", country: "China", coordinates: { lat: 34.4471, lng: 108.7516 } },
  { code: "HGH", name: "Hangzhou Xiaoshan", city: "Hangzhou", country: "China", coordinates: { lat: 30.2295, lng: 120.4344 } },
  { code: "KMG", name: "Kunming Changshui", city: "Kunming", country: "China", coordinates: { lat: 24.9924, lng: 102.7432 } },
  { code: "WUH", name: "Wuhan Tianhe", city: "Wuhan", country: "China", coordinates: { lat: 30.7838, lng: 114.2081 } },
  { code: "HKG", name: "Hong Kong International", city: "Hong Kong", country: "China", coordinates: { lat: 22.308, lng: 113.9185 } },
  { code: "MFM", name: "Macau International", city: "Macau", country: "China", coordinates: { lat: 22.1496, lng: 113.5915 } },
  { code: "TPE", name: "Taiwan Taoyuan", city: "Taipei", country: "Taiwan", coordinates: { lat: 25.0797, lng: 121.2342 } },
  { code: "SIN", name: "Changi Airport", city: "Singapore", country: "Singapore", coordinates: { lat: 1.3644, lng: 103.9915 } },
  { code: "KUL", name: "Kuala Lumpur International", city: "Kuala Lumpur", country: "Malaysia", coordinates: { lat: 2.7456, lng: 101.71 } },
  { code: "PEN", name: "Penang International", city: "Penang", country: "Malaysia", coordinates: { lat: 5.2972, lng: 100.2767 } },
  { code: "BKI", name: "Kota Kinabalu Intl", city: "Kota Kinabalu", country: "Malaysia", coordinates: { lat: 5.9372, lng: 116.0513 } },
  { code: "LGK", name: "Langkawi International", city: "Langkawi", country: "Malaysia", coordinates: { lat: 6.3297, lng: 99.7286 } },
  { code: "BKK", name: "Suvarnabhumi", city: "Bangkok", country: "Thailand", coordinates: { lat: 13.6900, lng: 100.7501 } },
  { code: "HKT", name: "Phuket International", city: "Phuket", country: "Thailand", coordinates: { lat: 8.1132, lng: 98.3169 } },
  { code: "CNX", name: "Chiang Mai International", city: "Chiang Mai", country: "Thailand", coordinates: { lat: 18.7668, lng: 98.9626 } },
  { code: "USM", name: "Samui Airport", city: "Koh Samui", country: "Thailand", coordinates: { lat: 9.5478, lng: 100.0622 } },
  { code: "CGK", name: "Soekarno-Hatta Intl", city: "Jakarta", country: "Indonesia", coordinates: { lat: -6.1256, lng: 106.6558 } },
  { code: "DPS", name: "Ngurah Rai International", city: "Bali", country: "Indonesia", coordinates: { lat: -8.7482, lng: 115.1672 } },
  { code: "SUB", name: "Juanda International", city: "Surabaya", country: "Indonesia", coordinates: { lat: -7.3798, lng: 112.787 } },
  { code: "JOG", name: "Yogyakarta International", city: "Yogyakarta", country: "Indonesia", coordinates: { lat: -7.9006, lng: 110.0578 } },
  { code: "MNL", name: "Ninoy Aquino International", city: "Manila", country: "Philippines", coordinates: { lat: 14.5086, lng: 121.0198 } },
  { code: "CEB", name: "Mactan-Cebu International", city: "Cebu", country: "Philippines", coordinates: { lat: 10.3076, lng: 123.9795 } },
  { code: "SGN", name: "Tan Son Nhat Intl", city: "Ho Chi Minh City", country: "Vietnam", coordinates: { lat: 10.8188, lng: 106.6519 } },
  { code: "HAN", name: "Noi Bai International", city: "Hanoi", country: "Vietnam", coordinates: { lat: 21.2212, lng: 105.807 } },
  { code: "DAD", name: "Da Nang International", city: "Da Nang", country: "Vietnam", coordinates: { lat: 16.0439, lng: 108.1992 } },
  { code: "PNH", name: "Phnom Penh International", city: "Phnom Penh", country: "Cambodia", coordinates: { lat: 11.5466, lng: 104.8441 } },
  { code: "REP", name: "Siem Reap International", city: "Siem Reap", country: "Cambodia", coordinates: { lat: 13.4107, lng: 103.8130 } },
  { code: "RGN", name: "Yangon International", city: "Yangon", country: "Myanmar", coordinates: { lat: 16.9073, lng: 96.1332 } },
  { code: "VTE", name: "Wattay International", city: "Vientiane", country: "Laos", coordinates: { lat: 17.9883, lng: 102.5633 } },
  { code: "BWN", name: "Brunei International", city: "Bandar Seri Begawan", country: "Brunei", coordinates: { lat: 4.9442, lng: 114.9283 } },
  { code: "DEL", name: "Indira Gandhi International", city: "New Delhi", country: "India", coordinates: { lat: 28.5562, lng: 77.1 } },
  { code: "BOM", name: "Chhatrapati Shivaji Maharaj", city: "Mumbai", country: "India", coordinates: { lat: 19.0896, lng: 72.8656 } },
  { code: "BLR", name: "Kempegowda International", city: "Bangalore", country: "India", coordinates: { lat: 13.1979, lng: 77.7063 } },
  { code: "MAA", name: "Chennai International", city: "Chennai", country: "India", coordinates: { lat: 12.9941, lng: 80.1709 } },
  { code: "HYD", name: "Rajiv Gandhi International", city: "Hyderabad", country: "India", coordinates: { lat: 17.2403, lng: 78.4294 } },
  { code: "CCU", name: "Netaji Subhas Chandra Bose", city: "Kolkata", country: "India", coordinates: { lat: 22.6547, lng: 88.4467 } },
  { code: "COK", name: "Cochin International", city: "Kochi", country: "India", coordinates: { lat: 10.152, lng: 76.4019 } },
  { code: "GOI", name: "Goa International", city: "Goa", country: "India", coordinates: { lat: 15.3809, lng: 73.8314 } },
  { code: "AMD", name: "Ahmedabad International", city: "Ahmedabad", country: "India", coordinates: { lat: 23.0772, lng: 72.6347 } },
  { code: "JAI", name: "Jaipur International", city: "Jaipur", country: "India", coordinates: { lat: 26.8242, lng: 75.8122 } },
  { code: "ISB", name: "Islamabad International", city: "Islamabad", country: "Pakistan", coordinates: { lat: 33.5605, lng: 72.8526 } },
  { code: "KHI", name: "Jinnah International", city: "Karachi", country: "Pakistan", coordinates: { lat: 24.9065, lng: 67.1609 } },
  { code: "LHE", name: "Allama Iqbal International", city: "Lahore", country: "Pakistan", coordinates: { lat: 31.5216, lng: 74.4036 } },
  { code: "CMB", name: "Bandaranaike International", city: "Colombo", country: "Sri Lanka", coordinates: { lat: 7.1808, lng: 79.8841 } },
  { code: "DAC", name: "Hazrat Shahjalal Intl", city: "Dhaka", country: "Bangladesh", coordinates: { lat: 23.8433, lng: 90.3978 } },
  { code: "KTM", name: "Tribhuvan International", city: "Kathmandu", country: "Nepal", coordinates: { lat: 27.6966, lng: 85.3591 } },
  { code: "MLE", name: "Velana International", city: "Malé", country: "Maldives", coordinates: { lat: 4.1918, lng: 73.5291 } },
  { code: "ULN", name: "Chinggis Khaan Intl", city: "Ulaanbaatar", country: "Mongolia", coordinates: { lat: 47.843, lng: 106.767 } },
  { code: "NQZ", name: "Nursultan Nazarbayev Intl", city: "Astana", country: "Kazakhstan", coordinates: { lat: 51.0222, lng: 71.4669 } },
  { code: "ALA", name: "Almaty International", city: "Almaty", country: "Kazakhstan", coordinates: { lat: 43.3521, lng: 77.0405 } },
  { code: "TAS", name: "Islam Karimov Intl", city: "Tashkent", country: "Uzbekistan", coordinates: { lat: 41.2581, lng: 69.2812 } },
  { code: "GYD", name: "Heydar Aliyev International", city: "Baku", country: "Azerbaijan", coordinates: { lat: 40.4675, lng: 50.0467 } },
  { code: "TBS", name: "Tbilisi International", city: "Tbilisi", country: "Georgia", coordinates: { lat: 41.6692, lng: 44.9547 } },
  { code: "EVN", name: "Zvartnots International", city: "Yerevan", country: "Armenia", coordinates: { lat: 40.1473, lng: 44.3959 } },
  { code: "FRU", name: "Manas International", city: "Bishkek", country: "Kyrgyzstan", coordinates: { lat: 43.0613, lng: 74.4776 } },
  { code: "DYU", name: "Dushanbe International", city: "Dushanbe", country: "Tajikistan", coordinates: { lat: 38.5433, lng: 68.825 } },
  { code: "ASB", name: "Ashgabat International", city: "Ashgabat", country: "Turkmenistan", coordinates: { lat: 37.9868, lng: 58.361 } },
  { code: "KBL", name: "Kabul International", city: "Kabul", country: "Afghanistan", coordinates: { lat: 34.5659, lng: 69.2124 } },

  // ── OCEANIA ────────────────────────────────────────────────
  { code: "SYD", name: "Sydney Airport", city: "Sydney", country: "Australia", coordinates: { lat: -33.9461, lng: 151.1772 } },
  { code: "MEL", name: "Melbourne Tullamarine", city: "Melbourne", country: "Australia", coordinates: { lat: -37.6733, lng: 144.8433 } },
  { code: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "Australia", coordinates: { lat: -27.3842, lng: 153.1175 } },
  { code: "PER", name: "Perth Airport", city: "Perth", country: "Australia", coordinates: { lat: -31.9403, lng: 115.9668 } },
  { code: "ADL", name: "Adelaide Airport", city: "Adelaide", country: "Australia", coordinates: { lat: -34.945, lng: 138.5306 } },
  { code: "CNS", name: "Cairns Airport", city: "Cairns", country: "Australia", coordinates: { lat: -16.8858, lng: 145.7554 } },
  { code: "OOL", name: "Gold Coast Airport", city: "Gold Coast", country: "Australia", coordinates: { lat: -28.1644, lng: 153.5047 } },
  { code: "DRW", name: "Darwin International", city: "Darwin", country: "Australia", coordinates: { lat: -12.4147, lng: 130.8769 } },
  { code: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand", coordinates: { lat: -37.0082, lng: 174.7917 } },
  { code: "CHC", name: "Christchurch Airport", city: "Christchurch", country: "New Zealand", coordinates: { lat: -43.4894, lng: 172.5322 } },
  { code: "WLG", name: "Wellington Airport", city: "Wellington", country: "New Zealand", coordinates: { lat: -41.3272, lng: 174.8053 } },
  { code: "ZQN", name: "Queenstown Airport", city: "Queenstown", country: "New Zealand", coordinates: { lat: -45.0211, lng: 168.7392 } },
  { code: "NAN", name: "Nadi International", city: "Nadi", country: "Fiji", coordinates: { lat: -17.7554, lng: 177.4432 } },
  { code: "PPT", name: "Faa'a International", city: "Papeete", country: "French Polynesia", coordinates: { lat: -17.5537, lng: -149.6071 } },
  { code: "NOU", name: "La Tontouta International", city: "Nouméa", country: "New Caledonia", coordinates: { lat: -22.0146, lng: 166.2129 } },
  { code: "APW", name: "Faleolo International", city: "Apia", country: "Samoa", coordinates: { lat: -13.8297, lng: -171.9978 } },
  { code: "TBU", name: "Fuaʻamotu International", city: "Nukuʻalofa", country: "Tonga", coordinates: { lat: -21.2412, lng: -175.1497 } },
  { code: "POM", name: "Jacksons International", city: "Port Moresby", country: "Papua New Guinea", coordinates: { lat: -6.0058, lng: 147.0069 } },

  // ── AFRICA ─────────────────────────────────────────────────
  { code: "CPT", name: "Cape Town International", city: "Cape Town", country: "South Africa", coordinates: { lat: -33.9715, lng: 18.6021 } },
  { code: "JNB", name: "O.R. Tambo International", city: "Johannesburg", country: "South Africa", coordinates: { lat: -26.1392, lng: 28.246 } },
  { code: "DUR", name: "King Shaka International", city: "Durban", country: "South Africa", coordinates: { lat: -29.6144, lng: 31.1197 } },
  { code: "MQP", name: "Kruger Mpumalanga Intl", city: "Nelspruit", country: "South Africa", coordinates: { lat: -25.3832, lng: 31.1056 } },
  { code: "PLZ", name: "Port Elizabeth Airport", city: "Port Elizabeth", country: "South Africa", coordinates: { lat: -33.985, lng: 25.6173 } },
  { code: "CAI", name: "Cairo International", city: "Cairo", country: "Egypt", coordinates: { lat: 30.1219, lng: 31.4056 } },
  { code: "SSH", name: "Sharm El Sheikh Intl", city: "Sharm El Sheikh", country: "Egypt", coordinates: { lat: 27.9773, lng: 34.3953 } },
  { code: "HRG", name: "Hurghada International", city: "Hurghada", country: "Egypt", coordinates: { lat: 27.1784, lng: 33.7994 } },
  { code: "LXR", name: "Luxor International", city: "Luxor", country: "Egypt", coordinates: { lat: 25.6741, lng: 32.7066 } },
  { code: "LOS", name: "Murtala Muhammed Intl", city: "Lagos", country: "Nigeria", coordinates: { lat: 6.5774, lng: 3.3212 } },
  { code: "ABV", name: "Nnamdi Azikiwe Intl", city: "Abuja", country: "Nigeria", coordinates: { lat: 9.0068, lng: 7.2632 } },
  { code: "PHC", name: "Port Harcourt International", city: "Port Harcourt", country: "Nigeria", coordinates: { lat: 5.0155, lng: 6.9496 } },
  { code: "NBO", name: "Jomo Kenyatta International", city: "Nairobi", country: "Kenya", coordinates: { lat: -1.3192, lng: 36.9278 } },
  { code: "MBA", name: "Moi International", city: "Mombasa", country: "Kenya", coordinates: { lat: -4.0348, lng: 39.5942 } },
  { code: "ADD", name: "Bole International", city: "Addis Ababa", country: "Ethiopia", coordinates: { lat: 8.9779, lng: 38.7993 } },
  { code: "CMN", name: "Mohammed V International", city: "Casablanca", country: "Morocco", coordinates: { lat: 33.3675, lng: -7.5898 } },
  { code: "RAK", name: "Marrakech Menara", city: "Marrakech", country: "Morocco", coordinates: { lat: 31.6069, lng: -8.0363 } },
  { code: "TNG", name: "Ibn Battouta Airport", city: "Tangier", country: "Morocco", coordinates: { lat: 35.7269, lng: -5.9169 } },
  { code: "FEZ", name: "Fès-Saïss Airport", city: "Fès", country: "Morocco", coordinates: { lat: 33.9273, lng: -4.978 } },
  { code: "AGA", name: "Al Massira Airport", city: "Agadir", country: "Morocco", coordinates: { lat: 30.325, lng: -9.4131 } },
  { code: "ALG", name: "Houari Boumediene", city: "Algiers", country: "Algeria", coordinates: { lat: 36.691, lng: 3.2154 } },
  { code: "ORN", name: "Ahmed Ben Bella Airport", city: "Oran", country: "Algeria", coordinates: { lat: 35.6239, lng: -0.6213 } },
  { code: "CZL", name: "Mohamed Boudiaf Airport", city: "Constantine", country: "Algeria", coordinates: { lat: 36.2760, lng: 6.6204 } },
  { code: "TUN", name: "Tunis-Carthage Intl", city: "Tunis", country: "Tunisia", coordinates: { lat: 36.851, lng: 10.2272 } },
  { code: "DJE", name: "Djerba–Zarzis Intl", city: "Djerba", country: "Tunisia", coordinates: { lat: 33.875, lng: 10.7755 } },
  { code: "TIP", name: "Mitiga International", city: "Tripoli", country: "Libya", coordinates: { lat: 32.401, lng: 13.276 } },
  { code: "DSS", name: "Blaise Diagne International", city: "Dakar", country: "Senegal", coordinates: { lat: 14.6701, lng: -17.0734 } },
  { code: "ABJ", name: "Félix-Houphouët-Boigny", city: "Abidjan", country: "Côte d'Ivoire", coordinates: { lat: 5.2614, lng: -3.9262 } },
  { code: "ACC", name: "Kotoka International", city: "Accra", country: "Ghana", coordinates: { lat: 5.6052, lng: -0.1668 } },
  { code: "DLA", name: "Douala International", city: "Douala", country: "Cameroon", coordinates: { lat: 4.0061, lng: 9.7194 } },
  { code: "NSI", name: "Yaoundé Nsimalen Intl", city: "Yaoundé", country: "Cameroon", coordinates: { lat: 3.7226, lng: 11.5533 } },
  { code: "FIH", name: "N'djili International", city: "Kinshasa", country: "DR Congo", coordinates: { lat: -4.3858, lng: 15.4446 } },
  { code: "FBM", name: "Lubumbashi International", city: "Lubumbashi", country: "DR Congo", coordinates: { lat: -11.5913, lng: 27.5309 } },
  { code: "LBV", name: "Léon-Mba International", city: "Libreville", country: "Gabon", coordinates: { lat: 0.4586, lng: 9.4123 } },
  { code: "BZV", name: "Maya-Maya Airport", city: "Brazzaville", country: "Congo", coordinates: { lat: -4.2517, lng: 15.253 } },
  { code: "PNR", name: "Pointe-Noire Airport", city: "Pointe-Noire", country: "Congo", coordinates: { lat: -4.8116, lng: 11.8866 } },
  { code: "DAR", name: "Julius Nyerere Intl", city: "Dar es Salaam", country: "Tanzania", coordinates: { lat: -6.8781, lng: 39.2026 } },
  { code: "JRO", name: "Kilimanjaro International", city: "Kilimanjaro", country: "Tanzania", coordinates: { lat: -3.4294, lng: 37.0745 } },
  { code: "ZNZ", name: "Abeid Amani Karume Intl", city: "Zanzibar", country: "Tanzania", coordinates: { lat: -6.222, lng: 39.2249 } },
  { code: "EBB", name: "Entebbe International", city: "Entebbe", country: "Uganda", coordinates: { lat: 0.0424, lng: 32.4435 } },
  { code: "KGL", name: "Kigali International", city: "Kigali", country: "Rwanda", coordinates: { lat: -1.9686, lng: 30.1395 } },
  { code: "BJM", name: "Melchior Ndadaye Intl", city: "Bujumbura", country: "Burundi", coordinates: { lat: -3.324, lng: 29.3185 } },
  { code: "MRU", name: "Sir Seewoosagur Ramgoolam", city: "Port Louis", country: "Mauritius", coordinates: { lat: -20.4302, lng: 57.6836 } },
  { code: "SEZ", name: "Seychelles International", city: "Mahé", country: "Seychelles", coordinates: { lat: -4.6743, lng: 55.5218 } },
  { code: "TNR", name: "Ivato International", city: "Antananarivo", country: "Madagascar", coordinates: { lat: -18.7969, lng: 47.4788 } },
  { code: "NOS", name: "Fascene Airport", city: "Nosy Be", country: "Madagascar", coordinates: { lat: -13.3121, lng: 48.3148 } },
  { code: "LUN", name: "Kenneth Kaunda Intl", city: "Lusaka", country: "Zambia", coordinates: { lat: -15.3308, lng: 28.4526 } },
  { code: "LVI", name: "Harry Mwanga Nkumbula Intl", city: "Livingstone", country: "Zambia", coordinates: { lat: -17.8218, lng: 25.8227 } },
  { code: "HRE", name: "Robert Gabriel Mugabe Intl", city: "Harare", country: "Zimbabwe", coordinates: { lat: -17.9318, lng: 31.0928 } },
  { code: "VFA", name: "Victoria Falls Airport", city: "Victoria Falls", country: "Zimbabwe", coordinates: { lat: -18.0959, lng: 25.839 } },
  { code: "WDH", name: "Hosea Kutako International", city: "Windhoek", country: "Namibia", coordinates: { lat: -22.4799, lng: 17.4709 } },
  { code: "GBE", name: "Sir Seretse Khama Intl", city: "Gaborone", country: "Botswana", coordinates: { lat: -24.5552, lng: 25.9182 } },
  { code: "MUN", name: "Maun Airport", city: "Maun", country: "Botswana", coordinates: { lat: -19.9726, lng: 23.4311 } },
  { code: "MPM", name: "Maputo International", city: "Maputo", country: "Mozambique", coordinates: { lat: -26.0408, lng: 32.5727 } },
  { code: "BJL", name: "Banjul International", city: "Banjul", country: "Gambia", coordinates: { lat: 13.338, lng: -16.6522 } },
  { code: "OUA", name: "Thomas Sankara Intl", city: "Ouagadougou", country: "Burkina Faso", coordinates: { lat: 12.3532, lng: -1.5124 } },
  { code: "BKO", name: "Modibo Keïta International", city: "Bamako", country: "Mali", coordinates: { lat: 12.5335, lng: -7.9499 } },
  { code: "NKC", name: "Nouakchott–Oumtounsy Intl", city: "Nouakchott", country: "Mauritania", coordinates: { lat: 18.31, lng: -15.9697 } },
  { code: "NIM", name: "Diori Hamani International", city: "Niamey", country: "Niger", coordinates: { lat: 13.4815, lng: 2.1835 } },
  { code: "NDJ", name: "N'Djamena International", city: "N'Djamena", country: "Chad", coordinates: { lat: 12.1337, lng: 15.034 } },
  { code: "KRT", name: "Khartoum International", city: "Khartoum", country: "Sudan", coordinates: { lat: 15.5895, lng: 32.5532 } },
  { code: "MGQ", name: "Aden Abdulle International", city: "Mogadishu", country: "Somalia", coordinates: { lat: 2.0144, lng: 45.3047 } },
  { code: "JIB", name: "Djibouti–Ambouli International", city: "Djibouti", country: "Djibouti", coordinates: { lat: 11.5473, lng: 43.1595 } },
  { code: "ASM", name: "Asmara International", city: "Asmara", country: "Eritrea", coordinates: { lat: 15.2919, lng: 38.9107 } },
  { code: "ROB", name: "Roberts International", city: "Monrovia", country: "Liberia", coordinates: { lat: 6.2338, lng: -10.3623 } },
  { code: "FNA", name: "Lungi International", city: "Freetown", country: "Sierra Leone", coordinates: { lat: 8.6164, lng: -13.1955 } },
  { code: "CKY", name: "Conakry International", city: "Conakry", country: "Guinea", coordinates: { lat: 9.5769, lng: -13.612 } },
  { code: "OXB", name: "Osvaldo Vieira Intl", city: "Bissau", country: "Guinea-Bissau", coordinates: { lat: 11.8948, lng: -15.6537 } },
  { code: "COO", name: "Cadjehoun Airport", city: "Cotonou", country: "Benin", coordinates: { lat: 6.3573, lng: 2.3844 } },
  { code: "LFW", name: "Gnassingbé Eyadéma Intl", city: "Lomé", country: "Togo", coordinates: { lat: 6.1656, lng: 1.2545 } },
  { code: "SSG", name: "Malabo International", city: "Malabo", country: "Equatorial Guinea", coordinates: { lat: 3.7553, lng: 8.7087 } },
  { code: "RAI", name: "Nelson Mandela Intl", city: "Praia", country: "Cape Verde", coordinates: { lat: 14.9245, lng: -23.4935 } },
  { code: "SID", name: "Amílcar Cabral Intl", city: "Sal", country: "Cape Verde", coordinates: { lat: 16.7414, lng: -22.9494 } },
  { code: "STP", name: "São Tomé International", city: "São Tomé", country: "São Tomé & Príncipe", coordinates: { lat: 0.3782, lng: 6.7125 } },
  { code: "RUN", name: "Roland Garros Airport", city: "Saint-Denis", country: "Réunion", coordinates: { lat: -20.8871, lng: 55.5103 } },
  { code: "HAH", name: "Prince Said Ibrahim Intl", city: "Moroni", country: "Comoros", coordinates: { lat: -11.5337, lng: 43.2719 } },
  { code: "BGF", name: "Bangui M'Poko Intl", city: "Bangui", country: "Central African Republic", coordinates: { lat: 4.3985, lng: 18.5188 } },
  { code: "MWZ", name: "Mwanza Airport", city: "Mwanza", country: "Tanzania", coordinates: { lat: -2.4445, lng: 32.9327 } },
  { code: "LLW", name: "Lilongwe International", city: "Lilongwe", country: "Malawi", coordinates: { lat: -13.7894, lng: 33.781 } },
  { code: "BLZ", name: "Chileka International", city: "Blantyre", country: "Malawi", coordinates: { lat: -15.6791, lng: 34.9740 } },
  { code: "LAD", name: "Quatro de Fevereiro Intl", city: "Luanda", country: "Angola", coordinates: { lat: -8.8584, lng: 13.2312 } },
  { code: "BEW", name: "Beira Airport", city: "Beira", country: "Mozambique", coordinates: { lat: -19.7964, lng: 34.9076 } },
  { code: "JUB", name: "Juba International", city: "Juba", country: "South Sudan", coordinates: { lat: 4.8721, lng: 31.6011 } },
  { code: "MTS", name: "King Mswati III Intl", city: "Manzini", country: "Eswatini", coordinates: { lat: -26.5290, lng: 31.3075 } },
  { code: "MSU", name: "Moshoeshoe I International", city: "Maseru", country: "Lesotho", coordinates: { lat: -29.4623, lng: 27.5525 } },
];
